### PR TITLE
[WIP] refactor snapshot.go

### PR DESCRIPTION
**Pull request by geekyd**
[WORK IN PROGRESS] Refactoring the file to reduce the number of branch points

Signed-off-by: Dilpreet Singh <singhsince94@gmail.com>

### CODE REVIEW

**Comment by geekyd** [comment]
@payes Its still work in progress :). I will improve & remove the WIP tag from the PR when I'm done

**Comment by kmova** [comment]
@geekyd -- Are you still working on this?

**Comment by geekyd** [comment]
@kmova Yes. Sorry about the delay I will update the PR soon.

**Comment by utkarshmani1997** [comment]
Thanks @geekyd for the refactoring. Closing this PR as the comments haven't been addressed since very long time. A new PR can be raised for the same :)

**Pull request closed without merging**
