### PR TITLE
Extracted common values and functions

### PR DESCRIPTION
**Pull request by codegagan**
fixes openebs/openebs#2169

### CODE REVIEW

**Comment by utkarshmani1997** [comment]
@codegagan there is problem in your code. It looks like type mismatch to me in first look. Kindly fix that.

**Comment by codegagan** [comment]
committed the fix, waiting for build status.

**Comment by codegagan** [comment]
Build is passed.

**Comment by utkarshmani1997** [comment]
@codegagan can you also sign your commits, DCO is failing

**Comment by codegagan** [comment]
@utkarshmani1997 Fixed the DCO.

**Comment by utkarshmani1997** [comment]
@codegagan you need to rebase your origin with the upstream

**Comment by codegagan** [comment]
@utkarshmani1997 done

**Comment by utkarshmani1997** [comment]
cc: @payes

**Pull request merged**
